name: Deploy Simple lambda demo
on: [push]
jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: run tests
        run: make test